name: pawprints
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.0+1
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.0.0
  image_picker: ^1.0.0
  flutter_image_compress: ^2.4.0
  image: ^4.2.0
  compressor: ^1.0.0
  flutter_svg: ^2.0.7
  asset_fill: ^2.0.0
  get: ^4.7.0
  flutter_bloc: ^9.1.0
  provider: ^6.1.4
  riverpod: ^2.6.1
  get_it: ^8.0.0
  dio: ^5.8.0
  retrofit: ^4.4.2
  chopper: ^8.1.0
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^15.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 05.02 - NOTE: flutter packages pub run build_runner build
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.3.12
  custom_lint: ^0.6.0
  json_serializable: ^6.9.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  riverpod_generator: ^2.4.2
  hive_generator: ^2.0.1
  retrofit_generator: ^9.1.9

flutter:
  uses-material-design: true

  assets: # 04.29 - NOTE: figma export 시 SVG 사용 권장
    - assets/datas/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icons/app_icon.png'
# 04.29 - NOTE: flutter pub run flutter_launcher_icons

flutter_native_splash:
  background_image: assets/datas/splash_background.png
  image: assets/datas/splash_image.png
  android: true
  ios: true
  fullscreen: true
# 04.29 - NOTE: flutter pub run flutter_native_splash:remove / flutter pub run flutter_native_splash:create